

# A replicaset is also a shard. There is no need to
# have a routers before each replicaset, but it could be possible.
# This configuration can also be edited through an api on the routers.
# However, it is also possible to just keep this file on each router
# instance, and restart each router separately to edit the file.
# Using a database for configurations however, can make this simpler.


# The alternative to config files is to just start the routers
# Then use the API to add and update replica sets

# A greate improvement is if we can use relays without having them as separate
# services running, and just use the logic on the routers. Or run a relay as
# a child process.
# Maybe it is possible to just use NewHTTP


# A router config is not necessary as the bind-addr could be passed as an argument.
[[router]]
name = "router1"
bind-addr = "0.0.0.0:5096"

[[replicaSet]]
name = "rs1"
    [[replicaSet.relay]]
        name = "relay1"
        location = "192.168.99.100:9096"
    [[replicaSet.replica]]
        name = "data1"
        location = "192.168.99.100:8086"
    [[replicaSet.replica]]
        name = "data2"
        location = "192.168.99.100:7086"

[[replicaSet]]
name = "rs2"
    [[replicaSet.relay]]
        name = "relay1"
        location = "192.168.99.100:29096"
    [[replicaSet.replica]]
        name = "data1"
        location = "192.168.99.100:28086"
    [[replicaSet.replica]]
        name = "data2"
        location = "192.168.99.100:27086"