[[router]]
name = "router1"
bind-addr = "0.0.0.0:5096"
    [[router.relays]]
        name = "relay1"
        location = "192.168.99.100:9096"
    [[router.dbs]]
        name = "data1"
        location = "192.168.99.100:8086"
    [[router.dbs]]
        name = "data2"
        location = "192.168.99.100:7086"